CREATE DATABASE IF NOT EXISTS db_identity;
CREATE DATABASE IF NOT EXISTS db_product;
CREATE DATABASE IF NOT EXISTS db_inventory;
CREATE DATABASE IF NOT EXISTS db_order;
CREATE DATABASE IF NOT EXISTS db_payment;
CREATE DATABASE IF NOT EXISTS db_notification;
CREATE DATABASE IF NOT EXISTS db_delivery;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
FLUSH PRIVILEGES;