version: "3.8"

services:
  # --- Database Service ---
  mariadb:
    image: mariadb:10.6
    platform: linux/amd64
    container_name: oms-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - oms-network
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # --- Cache Service ---
  redis:
    image: redis:alpine
    container_name: oms-redis
    ports:
      - "6379:6379"
    networks:
      - oms-network

  # --- RabbitMQ ---
  rabbitmq:
    image: rabbitmq:4.2.2-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - oms-network

  # --- Platform services
  discovery-server:
    build:
      context: ./backend
      dockerfile: discovery-server/Dockerfile
    container_name: oms-discovery
    ports:
      - "8761:8761"
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_RESTART_POLL_INTERVAL=2s
      - SPRING_DEVTOOLS_RESTART_QUIET_PERIOD=1s
      - SPRING_DEVTOOLS_RESTART_ADDITIONAL_PATHS=/app/target/classes,/common-library/target/classes
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./backend/discovery-server/target/classes:/app/target/classes
      - ./backend/common-library/target/classes:/common-library/target/classes
    networks:
      - oms-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  api-gateway:
    build:
      context: ./backend
      dockerfile: api-gateway/Dockerfile
    container_name: oms-gateway
    ports:
      - "8888:8888"
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_RESTART_POLL_INTERVAL=2s
      - SPRING_DEVTOOLS_RESTART_QUIET_PERIOD=1s
      - SPRING_DEVTOOLS_RESTART_ADDITIONAL_PATHS=/app/target/classes,/common-library/target/classes
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
    volumes:
      - ./backend/api-gateway/target/classes:/app/target/classes
      - ./backend/common-library/target/classes:/common-library/target/classes
    networks:
      - oms-network

  # --- Business Microservices
  identity-service:
    build:
      context: ./backend
      dockerfile: identity-service/Dockerfile
    container_name: oms-identity
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_RESTART_POLL_INTERVAL=2s
      - SPRING_DEVTOOLS_RESTART_QUIET_PERIOD=1s
      - SPRING_DEVTOOLS_RESTART_ADDITIONAL_PATHS=/app/target/classes,/common-library/target/classes
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/db_identity
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password
    depends_on:
      mariadb:
        condition: service_healthy
      discovery-server:
        condition: service_started
    volumes:
      - ./backend/identity-service/target/classes:/app/target/classes
      - ./backend/common-library/target/classes:/common-library/target/classes
    networks:
      - oms-network

  profile-service:
    build:
      context: ./backend
      dockerfile: profile-service/Dockerfile
    container_name: oms-profile
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_RESTART_POLL_INTERVAL=2s
      - SPRING_DEVTOOLS_RESTART_QUIET_PERIOD=1s
      - SPRING_DEVTOOLS_RESTART_ADDITIONAL_PATHS=/app/target/classes,/common-library/target/classes
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/db_profile
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password
    depends_on:
      mariadb:
        condition: service_healthy
      discovery-server:
        condition: service_started
      rabbitmq:
        condition: service_started
    volumes:
      - ./backend/profile-service/target/classes:/app/target/classes
      - ./backend/common-library/target/classes:/common-library/target/classes
    networks:
      - oms-network

  product-service:
    build:
      context: ./backend
      dockerfile: product-service/Dockerfile
    container_name: oms-product
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_RESTART_POLL_INTERVAL=2s
      - SPRING_DEVTOOLS_RESTART_QUIET_PERIOD=1s
      - SPRING_DEVTOOLS_RESTART_ADDITIONAL_PATHS=/app/target/classes,/common-library/target/classes
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/db_product
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      mariadb:
        condition: service_healthy
      discovery-server:
        condition: service_started
    volumes:
      - ./backend/product-service/target/classes:/app/target/classes
      - ./backend/common-library/target/classes:/common-library/target/classes
    networks:
      - oms-network

  inventory-service:
    build:
      context: ./backend
      dockerfile: inventory-service/Dockerfile
    container_name: oms-inventory
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_RESTART_POLL_INTERVAL=2s
      - SPRING_DEVTOOLS_RESTART_QUIET_PERIOD=1s
      - SPRING_DEVTOOLS_RESTART_ADDITIONAL_PATHS=/app/target/classes,/common-library/target/classes
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/db_inventory
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      mariadb:
        condition: service_healthy
      discovery-server:
        condition: service_started
    volumes:
      - ./backend/inventory-service/target/classes:/app/target/classes
      - ./backend/common-library/target/classes:/common-library/target/classes
    networks:
      - oms-network

  order-service:
    build:
      context: ./backend
      dockerfile: order-service/Dockerfile
    container_name: oms-order
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_RESTART_POLL_INTERVAL=2s
      - SPRING_DEVTOOLS_RESTART_QUIET_PERIOD=1s
      - SPRING_DEVTOOLS_RESTART_ADDITIONAL_PATHS=/app/target/classes,/common-library/target/classes
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/db_order
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      mariadb:
        condition: service_healthy
      discovery-server:
        condition: service_started
    volumes:
      - ./backend/order-service/target/classes:/app/target/classes
      - ./backend/common-library/target/classes:/common-library/target/classes
    networks:
      - oms-network
  payment-service:
    build:
      context: ./backend
      dockerfile: payment-service/Dockerfile
    container_name: oms-payment
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_RESTART_POLL_INTERVAL=2s
      - SPRING_DEVTOOLS_RESTART_QUIET_PERIOD=1s
      - SPRING_DEVTOOLS_RESTART_ADDITIONAL_PATHS=/app/target/classes,/common-library/target/classes
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/db_payment
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password
    depends_on:
      mariadb:
        condition: service_healthy
      discovery-server:
        condition: service_started
    volumes:
      - ./backend/payment-service/target/classes:/app/target/classes
      - ./backend/common-library/target/classes:/common-library/target/classes
    networks:
      - oms-network

  notification-service:
    build:
      context: ./backend
      dockerfile: notification-service/Dockerfile
    container_name: oms-notification
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_RESTART_POLL_INTERVAL=2s
      - SPRING_DEVTOOLS_RESTART_QUIET_PERIOD=1s
      - SPRING_DEVTOOLS_RESTART_ADDITIONAL_PATHS=/app/target/classes,/common-library/target/classes
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/db_notification
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password
    depends_on:
      mariadb:
        condition: service_healthy
      discovery-server:
        condition: service_started
    volumes:
      - ./backend/notification-service/target/classes:/app/target/classes
      - ./backend/common-library/target/classes:/common-library/target/classes
    networks:
      - oms-network

  delivery-service:
    build:
      context: ./backend
      dockerfile: delivery-service/Dockerfile
    container_name: oms-delivery
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_RESTART_POLL_INTERVAL=2s
      - SPRING_DEVTOOLS_RESTART_QUIET_PERIOD=1s
      - SPRING_DEVTOOLS_RESTART_ADDITIONAL_PATHS=/app/target/classes,/common-library/target/classes
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/db_delivery
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password
    depends_on:
      mariadb:
        condition: service_healthy
      discovery-server:
        condition: service_started
    volumes:
      - ./backend/delivery-service/target/classes:/app/target/classes
      - ./backend/common-library/target/classes:/common-library/target/classes
    networks:
      - oms-network

  orchestrator-service:
    build:
      context: ./backend
      dockerfile: orchestrator-service/Dockerfile
    container_name: oms-orchestrator
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_RESTART_POLL_INTERVAL=2s
      - SPRING_DEVTOOLS_RESTART_QUIET_PERIOD=1s
      - SPRING_DEVTOOLS_RESTART_ADDITIONAL_PATHS=/app/target/classes,/common-library/target/classes
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/db_saga
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password
    depends_on:
      mariadb:
        condition: service_healthy
      discovery-server:
        condition: service_started
    volumes:
      - ./backend/orchestrator-service/target/classes:/app/target/classes
      - ./backend/common-library/target/classes:/common-library/target/classes
    networks:
      - oms-network

networks:
  oms-network:
    driver: bridge

volumes:
  mariadb_data:
