server:
    port: 8082
spring:
    application:
        name: inventory-service
    datasource:
        url: jdbc:mariadb://${SPRING_DATASOURCE_HOST:mariadb}:3306/db_inventory
        username: root
        password: root
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    rabbitmq:
        host: ${SPRING_RABBITMQ_HOST:rabbitmq}
        port: ${SPRING_RABBITMQ_PORT:5672}
        username: ${SPRING_RABBITMQ_USERNAME:user}
        password: ${SPRING_RABBITMQ_PASSWORD:password}
        listener:
            simple:
                acknowledge-mode: manual
                max-concurrency: 3
                prefetch: 10
eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka/}

logging:
    level:
        com.oms.inventoryservice: INFO
        org.springframework.amqp: INFO
