server:
    port: 8080 
spring:
    application:
        name: identity-service 

    rabbitmq:
        host: ${SPRING_RABBITMQ_HOST:localhost}
        port: ${SPRING_RABBITMQ_PORT:5672}
        username: ${SPRING_RABBITMQ_USERNAME:user}
        password: ${SPRING_RABBITMQ_PASSWORD:password}

    datasource:
        url: jdbc:mariadb://localhost:3306/db_identity
        username: root
        password: root
        driver-class-name: org.mariadb.jdbc.Driver
        
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
eureka:
    client:
        service-url:
          defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    instance:
        prefer-ip-address: true
jwt:
  secret: "oms-super-secret-key-project-kien-truc-phan-mem-2026-xyz123"
  expiration: 86400000 