server:
  port: 8081
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mariadb://${SPRING_DATASOURCE_HOST:mariadb}:3306/db_product
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: 6379
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:demo}
  api-key: ${CLOUDINARY_API_KEY:demo}
  api-secret: ${CLOUDINARY_API_SECRET:demo}

