server:
    port: 8888
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true 
    routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**

        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/v1/deliveries/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/